title: Jan Leimkühler - Maschinenbauexperte
subtitle: CE-Kennzeichnung für den Sondermaschinenbau
keywords: CE-Kennzeichnun
baseurl: /
permalink: "/:year/:month/:day/:title/"
hubspot:

collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"

header:
  title: Jan Leimkühler - Maschinenbauexperte
  logo_img: images/logo/rgb_logo.svg
  has_nav: true
  nav:
    FAQ: "faq"
    Leistungen: "services"
    Kunden: "customers"
    Lösungen: "solutions"
    Blog: "blog"
    Infos: "infos"

footer:
  logo_img:
  tagline:
  content: © Ingenieurbüro Leimkühler UG (haftungsbeschränkt)


  contact_title: Direkter Kontakt
  contacts:
    Gesprächstermin buchen: "jan"
    Anfrageformular: "docs/D-2001-CL-Checkliste zur Angebotserstellung.pdf"

  products_title: Ing.-Büro Leimkühler
  products:
    Obere Findelstätte 7:
    49124 Georgsmarienhütte:
    Deutschland:
    jan.leimkuehler@ib-leimkuehler.de:

  nav_title: Unternehmen
  nav:
    Jobs: "company"
    Kunden: "customers"
    Leistungen: "services"
    Blog: "blog"
    Infos: "infos"
    Kontakt: "contact"

  legal_title: Rechtliches
  legal_nav:
    Impressum: "impressum"
    Datenschutz: "datenschutz"
    AGB: "agbs"

  social_title: Community

  has_subscribe: true
  subscribe_title: "Newsletter abonnieren"
  subscribe_content: "Melde Dich jetzt bei unserem Newsletter an und bleibe immer auf dem neusten Stand."

  # Select which share links to show in posts
share-links-active:
  linkedin: true

defaults:
  - scope:
      path: "drafts/**"
    values:
      sitemap: false
  - scope:
      path: "images/**"
    values:
      sitemap: false

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
