title: Jan Leimkühler - Maschinenbauexperte 
subtitle: Wir übernehmen für dich die komplette Abwicklung der THG-Prämie zum Höchstpreis, so kannst du am besten mit deinem E-Auto Geld verdienen. Einfach. Nachhaltig.
keywords: thg, quote, verkaufen, verdienen, höchstpreis, beste, e-auto, elektroauto, treibhausgasquote
baseurl: /
permalink: "/:year/:month/:day/:title/"
hubspot: 25801309

collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"

header:
  title: Jan Leimkühler - Maschinenbauexperte 
  logo_img: images/logo/rgb_logo.png
  has_nav: true
  nav:
    FAQ: "faq"
    Unternehmen: "company"
    Diensleistungen: "services"
    Kunden: "customers"
    Lösungen: "solutions"
    Kontakt: "contact"
    Blog: "blog"
    Infos: "infos"

footer:
  logo_img: images/logo/logo_white.svg
  tagline:
  content: "&copy; mint future GmbH. All rights reserved."
  links:
    - text: Impressum
      url: "/impressum"
      new_window: false
    - text: Datenschutz
      url: "/datenschutz"
      new_window: false
    - text: Status
      url: "http://status.wirkaufendeinethg.de/"
      new_window: true

  social_title: Community

  nav_title: Firma
  nav:
    FAQ: "faq"
    Unternehmen: "company"
    Diensleistungen: "services"
    Kunden: "customers"
    Lösungen: "solutions"
    Kontakt: "contact"
    Blog: "blog"
    Infos: "infos"

  products_title: Lösungen
  products:
    E-Auto: "e-auto"
    E-Roller: "e-roller"
    E-Bus: "e-bus"
    E-Nutzfahrzeug: "e-nutzfahrzeug"
    Ladestation: "ladestation"
    Autohaus: "autohaus"
    Stadtwerke: "stadtwerke"
  has_subscribe: true
  subscribe_title: "Newsletter abonnieren"
  subscribe_content: "Melde Dich jetzt bei unserem Newsletter an und bleibe immer auf dem neusten Stand. Wir berichten laufend zur THG Quote und Elektromobilität."

  # Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
defaults:
  - scope:
      path: "drafts/**"
    values:
      sitemap: false
  - scope:
      path: "images/**"
    values:
      sitemap: false

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
